package com.onboarding.backend.entity;

public enum NotificationType {
	PROJECT_CREATED,
	TASK_ASSIGNED,
	TASK_UPDATED,
	TASK_DELETED,
	PROJECT_ASSIGNMENT_UPDATED,
	PROJECT_PROGRESS_UPDATED,
	PROJECT_COMPLETED
}
